### ISSUE TITLE
Launcher translation outdated

### ISSUE THREAD

**Issue by NightFurySL2001** [skmedix/SKlauncher#105]
Some of the translated files in asset/launcher/lang/ is not up to date after pull request #71 (specifically ccommit 9f05d0d6e2cf7ace6cbd7f6bfea1e44146ed3ba4).
Mainly on string settings.alert.title, which is changed drastically from "Information" to "Required Restart".

The following files are (probably) out of date in this string (and other changes too):

- [ ] sklmessages_eo.properties (Informaĵo)
- [ ] sklmessages_es_ES.properties (Información)
- [ ] sklmessages_fr_FR.properties (Informations)
- [x] sklmessages_hu_HU.properties (Információ)
- [ ] sklmessages_nb_NO.properties (Informasjon)
- [ ] sklmessages_pt_BR.properties (Informação)
- [ ] sklmessages_tr_TR.properties (Bilgi)
- [x] sklmessages_vi_VN.properties (Thông tin)
- [x] sklmessages_zh_CN.properties (通知)

**Comment by Greg-21** [comment]
The "Required Restart" title is now partially fixed in all lang files in `ui-rework` branch. "Partially" means that I replaced the translated "Information" title with untranslated "Required Restart". Additionally, the title in some of the languages – Czech, Hungarian, Italian, Polish, Romanian, Ukrainian, Vietnamese and Chinese – are now fully fixed, which means they contain translated "Required Restart" title.
