### ISSUE TITLE
no mod Just Enough Itens precisamos de mais dois mods, codechicken e jei, o codechicken funciona muito bem, porem o jei faz com que quando termine de carregar ele volte para a tela inicial

### ISSUE THREAD

**Issue by Doller13** [skmedix/SKlauncher#226]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Doller13** [comment]
é o mod CODECHICKEN

**Comment by TheusKhan** [comment]
Olá, amigo. O problema relatado não tem nenhuma ligação com o launcher, podendo ser incompatibilidade entre os seus mods. Infelizmente, não podemos fazer nada para te ajudar.
Como você já encontrou o que está causando problemas, tente contatar o desenvolvedor do mod e relatar o bug. Obrigado.

This bug is caused by incompatibilities between mods. Contact the mod developer. The user already knows which mod is causing crashes. Issue can be closed.
