### ISSUE TITLE
Minecraft crashing in version 1.15.2

### ISSUE THREAD

**Issue by BRUNOKLK** [skmedix/SKlauncher#277]
My Minecraft on SKLauncher is crashing in version 1.15.2 in a new profile. What can I do?

**Comment by NightFurySL2001** [comment]
1. Check if you have the right Java version installed. It should be 64-bit version instead of 32-bit version.
2. Try to delete yout `.minecraft` folder in AppData and then re-download the Minecraft version.
3. Try using another version of Minecraft.

Report back if there's any more problem. Do close this issue when it is solved.
